export const LIST_CURSOS_START = 'LIST_CURSOS_START'
export const LIST_CURSOS_SUCCESS = 'LIST_CURSOS_SUCCESS'
export const LIST_CURSOS_FAIL = 'LIST_CURSOS_FAIL'
export const LIST_CURSOS_FINALLY = 'LIST_CURSOS_FINALLY'

export const CLEAR_CURSOS = 'CLEAR_CURSOS'

export const ADD_NEW_CURSO_START = 'ADD_NEW_CURSO_START'
export const ADD_NEW_CURSO_SUCCESS = 'ADD_NEW_CURSO_SUCCESS'
export const ADD_NEW_CURSO_FAIL = 'ADD_NEW_CURSO_FAIL'
export const ADD_NEW_CURSO_FINALLY = 'ADD_NEW_CURSO_FINALLY'

export const DELETE_CURSO_START = 'DELETE_CURSO_START'
export const DELETE_CURSO_SUCCESS = 'DELETE_CURSO_SUCCESS'
export const DELETE_CURSO_FAIL = 'DELETE_CURSO_FAIL'
export const DELETE_CURSO_FINALLY = 'DELETE_CURSO_FINALLY'

export const UPDATE_CURSO_START = 'UPDATE_CURSO_START'
export const UPDATE_CURSO_SUCCESS = 'UPDATE_CURSO_SUCCESS'
export const UPDATE_CURSO_FAIL = 'UPDATE_CURSO_FAIL'
export const UPDATE_CURSO_FINALLY = 'UPDATE_CURSO_FINALLY'