export const LIST_ESTUDIANTES_START = 'LIST_ESTUDIANTES_START'
export const LIST_ESTUDIANTES_SUCCESS = 'LIST_ESTUDIANTES_SUCCESS'
export const LIST_ESTUDIANTES_FAIL = 'LIST_ESTUDIANTES_FAIL'
export const LIST_ESTUDIANTES_FINALLY = 'LIST_ESTUDIANTES_FINALLY'

export const CLEAR_ESTUDIANTES = 'CLEAR_ESTUDIANTES'

export const ADD_NEW_ESTUDIANTE_START = 'ADD_NEW_ESTUDIANTE_START'
export const ADD_NEW_ESTUDIANTE_SUCCESS = 'ADD_NEW_ESTUDIANTE_SUCCESS'
export const ADD_NEW_ESTUDIANTE_FAIL = 'ADD_NEW_ESTUDIANTE_FAIL'
export const ADD_NEW_ESTUDIANTE_FINALLY = 'ADD_NEW_ESTUDIANTE_FINALLY'

export const DELETE_ESTUDIANTE_START = 'DELETE_ESTUDIANTE_START'
export const DELETE_ESTUDIANTE_SUCCESS = 'DELETE_ESTUDIANTE_SUCCESS'
export const DELETE_ESTUDIANTE_FAIL = 'DELETE_ESTUDIANTE_FAIL'
export const DELETE_ESTUDIANTE_FINALLY = 'DELETE_ESTUDIANTE_FINALLY'

export const UPDATE_ESTUDIANTE_START = 'UPDATE_ESTUDIANTE_START'
export const UPDATE_ESTUDIANTE_SUCCESS = 'UPDATE_ESTUDIANTE_SUCCESS'
export const UPDATE_ESTUDIANTE_FAIL = 'UPDATE_ESTUDIANTE_FAIL'
export const UPDATE_ESTUDIANTE_FINALLY = 'UPDATE_ESTUDIANTE_FINALLY'