export const LIST_MATRICULAS_START = 'LIST_MATRICULAS_START'
export const LIST_MATRICULAS_SUCCESS = 'LIST_MATRICULAS_SUCCESS'
export const LIST_MATRICULAS_FAIL = 'LIST_MATRICULAS_FAIL'
export const LIST_MATRICULAS_FINALLY = 'LIST_MATRICULAS_FINALLY'

export const GET_MATRICULAS_ESTUDIANTE_START = 'GET_MATRICULAS_ESTUDIANTE_START'
export const GET_MATRICULAS_ESTUDIANTE_SUCCESS = 'GET_MATRICULAS_ESTUDIANTE_SUCCESS'
export const GET_MATRICULAS_ESTUDIANTE_FAIL = 'GET_MATRICULAS_ESTUDIANTE_FAIL'
export const GET_MATRICULAS_ESTUDIANTE_FINALLY = 'GET_MATRICULAS_ESTUDIANTE_FINALLY'

export const CLEAR_MATRICULAS = 'CLEAR_MATRICULAS'
export const CLEAR_MATRICULAS_ESTUDIANTE = 'CLEAR_MATRICULAS_ESTUDIANTE'

export const ADD_NEW_MATRICULA_START = 'ADD_NEW_MATRICULA_START'
export const ADD_NEW_MATRICULA_SUCCESS = 'ADD_NEW_MATRICULA_SUCCESS'
export const ADD_NEW_MATRICULA_FAIL = 'ADD_NEW_MATRICULA_FAIL'
export const ADD_NEW_MATRICULA_FINALLY = 'ADD_NEW_MATRICULA_FINALLY'

export const SELECT_MATRICULA_ITEM = 'SELECT_MATRICULA_ITEM'

export const GET_MATRICULA_START = 'GET_MATRICULA_START'
export const GET_MATRICULA_SUCCESS = 'GET_MATRICULA_SUCCESS'
export const GET_MATRICULA_FAIL = 'GET_MATRICULA_FAIL'
export const GET_MATRICULA_FINALLY = 'GET_MATRICULA_FINALLY'