export const BUILD_MENU_START = 'BUILD_MENU_START'
export const BUILD_MENU_SUCCESS = 'BUILD_MENU_SUCCESS'
export const BUILD_MENU_FAIL = 'BUILD_MENU_FAIL'
export const BUILD_MENU_FINALLY = 'BUILD_MENU_FINALLY'